name: DCO Check

on:
  pull_request:
    branches-ignore:
      - renovate/**

jobs:
  check:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@416cafbc9c07f26219d09981d9ac49ce29b5bfea # v1