name: DCO Check

on:
  pull_request:
    branches-ignore:
      - renovate/**

jobs:
  check:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@43e19574828cd1ef1c7907849b6ba0f3b5530cfe # v1