name: Go Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.25.x'

      - name: Install dependencies
        run: go get .

      - name: Generate Mocks and Run Tests
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report@latest
          go test -coverprofile=coverage.txt -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2
        with:
          paths: report.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}